### ISSUE TITLE
rDNS is broken in latest Windows release (only tested with binaries)

### ISSUE THREAD

**Issue by nazihhawi** [wez/atomicparsley#66]
rDNS tagging seems to be broken in latest Windows release. Starting with a blank input file or wiping any existing metadata in it before writing rDNS does not make a difference, and neither does writing in place or to temp output.

For example:

`AtomicParsley.exe Test.m4a --preserveTime --metaEnema`

`AtomicParsley.exe Test.m4a --preserveTime --rDNSatom " 00001BAB 00001CB3 000093C6 00009D77 0001145F 0001E1B9 00007C14 00007A19 000188D6 0001BB5B" name=iTunNORM domain=com.apple.iTunes`

writes metadata to `iTun` "atom" on domain `com.apple.iTunes`

Testing with `AtomicParsley.exe Test.m4a -t` yields:

`Atom "----" [com.apple.iTunes;iTun] contains:  00001BAB 00001CB3 000093C6 00009D77 0001145F 0001E1B9 00007C14 00007A19 000188D6 0001BB5B`

Some quick tests show that anything beyond the first 4 chars of the atom name are being truncated. Even worse, repeating the process ends up with multiple `iTun` "atoms".

EDIT 1: Running Windows 64-bit, tested with both AP 32 and 64. Same issue.

EDIT 2: I can confirm that this regression seems to have been introduced with the 2022 release. The [20210715.151551.e7ad03a](https://github.com/wez/atomicparsley/releases/tag/20210715.151551.e7ad03a) release works as expected.

**Comment by wilhuff** [comment]
Hm. I'm reading through #62 (and #44) and I don't think the proposed fix in #71 is quite right. Based on the way the reading code works, it seems to expect a 12-byte header in the atom and the actual rdns name should come after. I still can't account for why the original code triggered an ASAN error.

**Comment by wilhuff** [comment]
OK, the source of the 12 here is that the name atom is a ["full atom"](https://developer.apple.com/documentation/quicktime-file-format/name_atom). These include the usual 4-byte size, the 4-byte type code (`"name"`), and 4-bytes of version and flags fields. Therefore UTF-8 encoding of the name must start 12 bytes from the beginning. The reading code that expects to skip the first 12 bytes of the atom to get to the name is definitely correct.

The writing side of this is a mess. Reverting the changes in d86a31a099c65cfd4a122fec82ba0f5c3c6954c0 isn't enough. The trouble is that `APar_InterjectNewAtom` is confusing the meaning of the `atom_length` argument. On the one hand, it seems to mean that it's the initial length of the atom, before putting any data into it:

https://github.com/wez/atomicparsley/blob/171e8aeba2ca486d0a9049341ef91594683663ea/src/parsley.cpp#L2386

When binary data is appended to the atom, `APar_atom_Binary_Put` bumps `AtomicLength`.

This is why the code prior to d86a31a099c65cfd4a122fec82ba0f5c3c6954c0 worked for `"iTunMOVI"`: `AtomicLength` would initially be 12, reflecting the length of the full box header, and then `AtomicLength` would be 20 after appending the binary data. d86a31a099c65cfd4a122fec82ba0f5c3c6954c0 breaks this by making `AtomicLength` initially 8 and ends up at 16. Even though `"iTunMOVI"` is written into the buffer, only `AtomicLength`-worth is written out, resulting in the truncation we're seeing at HEAD.

On the other hand, `atom_length` is also used to compute the size of the `AtomicData` buffer:

https://github.com/wez/atomicparsley/blob/171e8aeba2ca486d0a9049341ef91594683663ea/src/parsley.cpp#L2389-L2394

This is why d86a31a099c65cfd4a122fec82ba0f5c3c6954c0 makes longer names succeed.  Writes via `APar_atom_Binary_Put` don't care about value of `AtomicLength`--they're always written relative to `AtomicData` plus `atomic_data_offset`, which is always 0 for names.

However, this isn't correct either: if you write a 20-byte name, the resulting `AtomicLength` will be 40, when it really should be 12 + 20 = 32 (this is the double-counting I thought I was seeing earlier). This wastes space in the written atom. It ends up looking like it works though: when writing, the `AtomicData` buffer was allocated by `calloc`, which zeroes its contents. When reading, any excess bytes past the end of user data look like a null terminator.  These are disregarded because it is treated as a string for display purposes. 

Interestingly, `APar_atom_Binary_Put` does a length check:

https://github.com/wez/atomicparsley/blob/171e8aeba2ca486d0a9049341ef91594683663ea/src/parsley.cpp#L2678-L2687

... but this isn't related to the size of the buffer at all: `MAXDATA_PAYLOAD` isn't used for the allocation of the `AtomicData` buffer here. Even worse, for data that might exceed that 1256-byte limit (e.g. very, very long names) this will result in needless truncation, even though the buffer could have been long enough to support a longer value.

The cheapest fix is therefore to just allocate the `AtomicData` buffer as containing `MAXDATA_PAYLOAD` bytes, similar to the way `APar_MetaData_atom_Init` does it:

https://github.com/wez/atomicparsley/blob/171e8aeba2ca486d0a9049341ef91594683663ea/src/parsley.cpp#L3274-L3279

Then the existing length check will just do its job. We'll waste ~3 KB of RAM for each reverse DNS name (in the "----", "mean", and "name" atoms) but we won't have to update all 11 sites that allocate or reassign the `AtomicData` pointer to account for anything more complicated.
